// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkinInfo 一个样式包（与前端约定一致）。
 * 
 * 除了 Go 侧自己用得上的几个字段（Module/Styles/Dir），这里把**清单原文**
 * 一并下发给前端：契约的字段解析放在前端一处（frontend/packages/player-skins），
 * 后端不再逐字段镜像一遍 —— 镜像就会出现"两边字段名不一致"的静默漂移。
 * @typedef {Object} SkinInfo
 * @property {string} id
 * @property {string} name
 * @property {string} [version]
 * @property {string} module - 相对该样式目录的入口 js
 * @property {string[] | null} styles - 相对该样式目录的 css 文件
 * @property {boolean} builtin
 * @property {string} source - builtin | data（排错用）
 * @property {any} manifest - 归一化后的清单（见 normalizeManifest）
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
