// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkinInfo 一个皮肤包（与前端 SkinInfo 对应）。
 * @typedef {Object} SkinInfo
 * @property {string} id
 * @property {string} name
 * @property {string} [version]
 * @property {string} module - 相对该皮肤目录的入口 js，默认 skin.js
 * @property {string[] | null} styles - 相对该皮肤目录的 css 文件
 * @property {boolean} builtin
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
