// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Measurement 一首歌的响度测量结果。
 * 
 * ★ 这里**刻意没有** Target / Gain 字段。
 * 
 * 它们曾经在结构体里，后果就是「换挡位时整条记录判为过期并删除」——
 * 用户从「较响(-14)」切到「默认(-16)」，之前在 -14 算好的补偿全没了。
 * 测量结果是文件的固有量，不该带任何与用户设置相关的字段 —— 把这条约束
 * 写进类型里，比写在注释里更不容易被后人改回去。
 * @typedef {Object} Measurement
 * @property {string} path
 * @property {number} size
 * @property {number} modTime
 * @property {number} [algo] - Algo 是测量算法版本。算法变了旧结果不可用（见 AlgoVersion）。
 * @property {number} integrated - 整合响度 LUFS
 * @property {number} truePeak - 真峰值 dBTP
 * @property {number} lra - 响度范围 LU
 * @property {number} threshold - 相对门限 LUFS
 * @property {boolean} [measured] - false 表示「测过但拿不到数据」
 * @property {number} measuredAt
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
