// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 提供「设置 → 关于」需要的那点宿主能力：读版本号、
 * 用系统默认浏览器打开外部链接。
 * 
 * 为什么这两件事必须由 Go 侧做：
 *   - 版本号写在前端就会和打包元数据各存一份，迟早对不上；
 *   - 页面跑在 WebView2 里且受 CSP 限制，window.open 只会开一个受 WebView
 *     管理的窗口（不是用户熟悉的浏览器），必须由宿主进程调 ShellExecute ——
 *     Wails 把它暴露成 app.Browser.OpenURL。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

/**
 * OpenURL 用系统默认浏览器打开一个外部链接。
 * 
 * 只放行 http / https，并且要求带主机名：这个参数最终会交给 ShellExecute，
 * 不做校验的话，一个 file:// 或自定义协议就能被页面（或注入进来的脚本）
 * 拿来拉起本机上的任意程序 —— 那已经不是「打开链接」了。
 * @param {string} raw
 * @returns {$CancellablePromise<void>}
 */
export function OpenURL(raw) {
    return $Call.ByID(790318107, raw);
}

/**
 * Version 返回应用版本号，例如 "0.1.0"。
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(1828333558);
}
