// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CoverService 管理歌曲封面：联网搜索、本地缓存、以及（可选）写回歌曲元数据。
 * 
 * 三个概念要分清：
 *  1. **来源**（coverfetch）：从 iTunes / 网易云 / Deezer / MusicBrainz 找一个候选图；
 *  2. **缓存**（metacache）：把选中的图存到缓存目录，这样离线也能用、
 *     也不会每次进详情页都去联网；
 *  3. **写回**（metacache.EmbedCover）：按用户设置决定要不要写进歌曲文件本身。
 * 
 * 前两步永远成功（只要缓存目录可写），第三步失败只降级不影响功能。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Apply 把用户选中的封面设为这首歌的封面。
 * 
 * 传 imageURL 时先下载；传 previewDataURL 时直接解码（前端预览里已经有字节了，
 * 不用再下一遍）。写完缓存后按设置决定是否写回歌曲文件。
 * 
 * embed 由调用方显式传入（nil = 按配置走）。
 * @param {string} songID
 * @param {string} imageURL
 * @param {string} previewDataURL
 * @returns {$CancellablePromise<$models.CoverResult>}
 */
export function Apply(songID, imageURL, previewDataURL) {
    return $Call.ByID(519515730, songID, imageURL, previewDataURL);
}

/**
 * ApplyWith 与 Apply 相同，但可以显式指定是否写回歌曲文件。
 * 
 * 为什么不让服务自己读配置：配置是从前端同步过来的，而前端是防抖 400ms
 * 批量推送的。如果调用方刚改了设置就立刻换封面，服务这边读到的很可能还是旧值
 * （实测就是这个原因导致「明明开了写回，结果没写」）。显式传入就没有这个竞态。
 * @param {string} songID
 * @param {string} imageURL
 * @param {string} previewDataURL
 * @param {boolean | null} embed
 * @returns {$CancellablePromise<$models.CoverResult>}
 */
export function ApplyWith(songID, imageURL, previewDataURL, embed) {
    return $Call.ByID(1774576670, songID, imageURL, previewDataURL, embed);
}

/**
 * CacheStats 缓存目录概况（设置界面展示）。
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function CacheStats() {
    return $Call.ByID(2998993659);
}

/**
 * ClearCache 清空缓存（封面 + 歌词）。已经写回文件的标签不受影响。
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function ClearCache() {
    return $Call.ByID(4241505431);
}

/**
 * Current 读取这首歌当前生效的封面（缓存优先）。
 * @param {string} songID
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Current(songID) {
    return $Call.ByID(3901355899, songID);
}

/**
 * Request 用户手动指定一个封面地址（自己粘贴图片链接）。
 * @param {string} rawURL
 * @returns {$CancellablePromise<$models.CoverResult>}
 */
export function Fetch(rawURL) {
    return $Call.ByID(238681278, rawURL);
}

/**
 * Lookup 联网为某首**本地歌曲**找封面。
 * 
 * 只返回候选与预览，不落盘 —— 用户可能连着看几个候选再决定用哪个。
 * 
 * override 允许调用方临时覆盖标题/歌手/专辑：下载下来的文件本来没有标签
 * （标题是从文件名推出来的），直接拿去搜基本不可能命中，而用户往往
 * 心里清楚这首歌是什么。传空 map 就按曲库里的元数据搜。
 * @param {string} songID
 * @param {{ [_ in string]?: any } | null} override
 * @returns {$CancellablePromise<$models.CoverResult>}
 */
export function Lookup(songID, override) {
    return $Call.ByID(572455644, songID, override);
}

/**
 * OpenCacheDir 在文件管理器里打开缓存目录。
 * @param {string} kind
 * @returns {$CancellablePromise<void>}
 */
export function OpenCacheDir(kind) {
    return $Call.ByID(1656170295, kind);
}

/**
 * Reset 恢复原始封面：删掉缓存里的覆盖图。
 * 
 * 注意写回文件的封面**无法撤销**（我们不会备份用户的原始标签），
 * 所以这里明确告诉前端：只清缓存，文件里已经写进去的不动。
 * @param {string} songID
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Reset(songID) {
    return $Call.ByID(1598057437, songID);
}

/**
 * WriteCacheToFiles 把缓存目录里已有的封面 + 歌词写进对应的歌曲文件。
 * 
 * 返回统计：total（有缓存可写的歌曲数）/ written / skipped（不支持写标签的格式）/
 * failed / covers / lyrics（分别写成功的份数）/ bytes（读了多少缓存数据）。
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function WriteCacheToFiles() {
    return $Call.ByID(2637958259);
}
