// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ConfigService from "./configservice.js";
import * as CoverService from "./coverservice.js";
import * as DownloadService from "./downloadservice.js";
import * as LibraryService from "./libraryservice.js";
import * as LoudnessService from "./loudnessservice.js";
import * as LyricsService from "./lyricsservice.js";
import * as MediaService from "./mediaservice.js";
import * as OnlineService from "./onlineservice.js";
import * as PlaylistService from "./playlistservice.js";
import * as ThemeService from "./themeservice.js";
import * as WindowService from "./windowservice.js";
export {
    ConfigService,
    CoverService,
    DownloadService,
    LibraryService,
    LoudnessService,
    LyricsService,
    MediaService,
    OnlineService,
    PlaylistService,
    ThemeService,
    WindowService
};

import * as $models from "./models.js";

/**
 * Result 一次封面操作的结果（前端弹层直接用这个渲染）。
 * @typedef {$models.CoverResult} CoverResult
 */
