// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LyricsService 歌词接口
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lyrics$0 from "./internal/lyrics/models.js";

/**
 * Load 按设置里的优先级加载歌词
 * @param {string} songID
 * @returns {$CancellablePromise<lyrics$0.Result>}
 */
export function Load(songID) {
    return $Call.ByID(1930549317, songID);
}
