// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MediaService 音频播放地址
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

/**
 * State 返回播放服务状态（前端据此提示「需安装 ffmpeg」）
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function State() {
    return $Call.ByID(4253167110);
}

/**
 * URL 返回某首歌的播放地址
 * @param {string} songID
 * @returns {$CancellablePromise<string>}
 */
export function URL(songID) {
    return $Call.ByID(3334933326, songID);
}
