// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as http$0 from "../net/http/models.js";

/**
 * CoverLookup 返回一首歌的封面地址（同源）。没找到时 available=false，
 * 前端据此「不显示封面」而不是留一个破图。
 * 
 * 走的是 coverfetch 的 Resolve（挑候选 → 下载 → 体检），因此返回的地址
 * 一定是一张**能显示、且不是纯白占位图**的图；白图会被当成「没找到」。
 * @param {string} title
 * @param {string} artist
 * @param {string} album
 * @param {number} durationMS
 * @param {string} fallback
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function CoverLookup(title, artist, album, durationMS, fallback) {
    return $Call.ByID(179773359, title, artist, album, durationMS, fallback);
}

/**
 * CoverProviders 返回已注册的封面来源（设置界面展示用）。
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function CoverProviders() {
    return $Call.ByID(338792953);
}

/**
 * @param {string} provider
 * @param {string} id
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function FetchLyrics(provider, id) {
    return $Call.ByID(725258170, provider, id);
}

/**
 * @returns {$CancellablePromise<http$0.Handler>}
 */
export function Handler() {
    return $Call.ByID(1858318818);
}

/**
 * InvalidateCovers 清空封面缓存（设置里改了来源或用户点「重新抓取」时用）。
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function InvalidateCovers() {
    return $Call.ByID(79488115);
}

/**
 * Lyrics 自动匹配并抓取一首歌的歌词（在线试听曲目用）。
 * 
 * 标题与歌手都要传给聚合器：评分靠它们做实体对齐，只给关键词会让所有候选
 * 都落在「信息不足」的基础分上，翻唱/Live 版很容易被选成第一名。
 * @param {string} title
 * @param {string} artist
 * @param {number} duration
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Lyrics(title, artist, duration) {
    return $Call.ByID(2678065822, title, artist, duration);
}

/**
 * LyricsProviders 返回已注册的在线歌词来源（界面展示/排查用）。
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function LyricsProviders() {
    return $Call.ByID(1413160088);
}

/**
 * @param {string} keyword
 * @param {number} page
 * @param {number} pageSize
 * @returns {$CancellablePromise<({ [_ in string]?: any } | null)[] | null>}
 */
export function Search(keyword, page, pageSize) {
    return $Call.ByID(605637138, keyword, page, pageSize);
}

/**
 * SearchLyrics 手动匹配歌词：按用户给的关键词搜索候选。
 * 
 * 三个参数各有用途，**不要合并**：
 *   - keyword 是用户在输入框里写/改的搜索词，喂给各来源做全文搜索；
 *   - title / artist 是这首歌的元数据，用于**打分排序**。
 * 
 * 早期实现只传了 keyword（还把它当成了 title），于是打分函数拿不到标题与歌手，
 * 所有候选都落在同一个基础分上 —— 结果就是「翻唱版排在原唱前面」，
 * 用户得自己在列表里找。
 * @param {string} keyword
 * @param {string} title
 * @param {string} artist
 * @param {number} duration
 * @returns {$CancellablePromise<({ [_ in string]?: any } | null)[] | null>}
 */
export function SearchLyrics(keyword, title, artist, duration) {
    return $Call.ByID(3637869574, keyword, title, artist, duration);
}
