// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkinService 播放界面皮肤（样式包）接口。
 * 
 * 与 ThemeService 的分工：
 *   - ThemeService 管的是「只换颜色令牌的 CSS 主题」；
 *   - SkinService 管的是「带 JS 入口 + 多份 CSS 的完整样式包」。
 * 
 * 皮肤资源不通过 Wails 绑定回传（那会变成把整个皮肤塞进内存），
 * 而是由 asset server 在 /skins/ 前缀下同源托管，前端直接 import 拿。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as skins$0 from "./internal/skins/models.js";

/**
 * Dir 皮肤根目录路径
 * @returns {$CancellablePromise<string>}
 */
export function Dir() {
    return $Call.ByID(257920803);
}

/**
 * List 皮肤列表
 * @returns {$CancellablePromise<skins$0.SkinInfo[] | null>}
 */
export function List() {
    return $Call.ByID(2450810548);
}

/**
 * Reload 重新扫描皮肤目录（用户在外部新增/修改皮肤后调用）
 * @returns {$CancellablePromise<skins$0.SkinInfo[] | null>}
 */
export function Reload() {
    return $Call.ByID(3248083889);
}

/**
 * RevealDir 在资源管理器中打开皮肤目录
 * @returns {$CancellablePromise<void>}
 */
export function RevealDir() {
    return $Call.ByID(1838209424);
}
