// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ThemeService 主题接口
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as theme$0 from "./internal/theme/models.js";

/**
 * Dir 主题目录路径
 * @returns {$CancellablePromise<string>}
 */
export function Dir() {
    return $Call.ByID(2215236143);
}

/**
 * List 主题列表
 * @returns {$CancellablePromise<theme$0.Info[] | null>}
 */
export function List() {
    return $Call.ByID(3105169408);
}

/**
 * Load 主题 CSS 原文
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function Load(id) {
    return $Call.ByID(4291046516, id);
}

/**
 * Reload 重新扫描主题目录（用户在外部新增文件后调用）
 * @returns {$CancellablePromise<theme$0.Info[] | null>}
 */
export function Reload() {
    return $Call.ByID(1266872413);
}

/**
 * RevealDir 在资源管理器中打开主题目录
 * @returns {$CancellablePromise<void>}
 */
export function RevealDir() {
    return $Call.ByID(3170006476);
}
