// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService 窗口控制
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Backdrop 返回窗口原生材质（Mica / Acrylic…）的状态。
 * 
 * 材质只能在创建窗口时指定，所以这里同时给出「配置里的值」和「窗口当前
 * 真正生效的值」，前端据此提示用户是否需要重启。
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Backdrop() {
    return $Call.ByID(2753426771);
}

/**
 * Close 关闭窗口
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(3687130319);
}

/**
 * DesktopLyricsState 读当前状态。
 * 
 * 歌词窗口加载完成后用它做一次初始同步：事件是「之后」才来的，
 * 不主动拉一次的话，新窗口会一直等到下一次换行才有内容。
 * @returns {$CancellablePromise<$models.desktopLyricsSnapshot>}
 */
export function DesktopLyricsState() {
    return $Call.ByID(3272880628);
}

/**
 * DesktopLyricsTouched 报告「桌面歌词开关是否已经被用户/前端操作过」。
 * 
 * 启动恢复的兜底路径用它来决定要不要出手：用户已经自己做过选择，
 * 恢复逻辑就必须退让，不能过一会儿又把窗口冒出来。
 * @returns {$CancellablePromise<boolean>}
 */
export function DesktopLyricsTouched() {
    return $Call.ByID(2596763195);
}

/**
 * DesktopWallpaperState 读当前状态。
 * 
 * 背景歌词窗口加载完成后用它做一次初始同步：事件是「之后」才来的，
 * 不主动拉一次的话，新窗口会一直空着直到下一次换行。
 * @returns {$CancellablePromise<$models.desktopWallpaperSnapshot>}
 */
export function DesktopWallpaperState() {
    return $Call.ByID(80366688);
}

/**
 * DesktopWallpaperTouched 报告「背景歌词开关是否已经被用户/前端操作过」。
 * 
 * 与 DesktopLyricsTouched 同一个用途：启动恢复的兜底路径靠它退让。
 * @returns {$CancellablePromise<boolean>}
 */
export function DesktopWallpaperTouched() {
    return $Call.ByID(4099891399);
}

/**
 * IsFullscreen 当前是否全屏
 * @returns {$CancellablePromise<boolean>}
 */
export function IsFullscreen() {
    return $Call.ByID(1414357132);
}

/**
 * IsMaximized 当前是否最大化
 * @returns {$CancellablePromise<boolean>}
 */
export function IsMaximized() {
    return $Call.ByID(1152965621);
}

/**
 * MarkDesktopLyricsReady 由歌词窗口在加载完成后调用，立刻把状态推给自己。
 * 
 * 页面加载完成与窗口创建之间有时序差：创建时推的那一次事件页面可能还没
 * 注册好监听，所以页面这边必须主动要一次。
 * @returns {$CancellablePromise<$models.desktopLyricsSnapshot>}
 */
export function MarkDesktopLyricsReady() {
    return $Call.ByID(4065798619);
}

/**
 * MarkDesktopWallpaperReady 由背景歌词窗口在加载完成后调用，立刻把状态推给自己。
 * 
 * 页面加载完成与窗口创建之间有时序差：创建时推的那一次事件页面可能还没
 * 注册好监听，所以页面这边必须主动要一次。
 * @returns {$CancellablePromise<$models.desktopWallpaperSnapshot>}
 */
export function MarkDesktopWallpaperReady() {
    return $Call.ByID(1378957625);
}

/**
 * Minimize 最小化
 * @returns {$CancellablePromise<void>}
 */
export function Minimize() {
    return $Call.ByID(3971742233);
}

/**
 * Restart 重启应用：先拉起一个新的自己，再退出当前进程。
 * 
 * 原生材质这类「只能在创建窗口时指定」的选项靠它生效。启动失败时不会退出，
 * 把错误交回前端提示，免得用户点了重启反而把应用关掉。
 * @returns {$CancellablePromise<void>}
 */
export function Restart() {
    return $Call.ByID(542969608);
}

/**
 * SetDesktopLyrics 打开/关闭桌面歌词窗口。
 * 
 * 由底栏「桌面歌词」按钮与设置里的同名开关调用。
 * 
 * 它与「桌面背景歌词」是一组单选按钮（见 desktop_wallpaper.go#setDesktopMode）：
 * 打开窗口歌词会先把背景歌词关掉，反过来也一样。
 * @param {boolean} on
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function SetDesktopLyrics(on) {
    return $Call.ByID(285307357, on);
}

/**
 * SetDesktopWallpaper 打开/关闭桌面背景歌词窗口。
 * 
 * 由底栏「桌面背景歌词」按钮与设置里的同名开关调用。
 * 与桌面歌词二选一：打开它会把窗口歌词先关掉（见 setDesktopMode）。
 * @param {boolean} on
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function SetDesktopWallpaper(on) {
    return $Call.ByID(3416753057, on);
}

/**
 * SetFullscreen 全屏开关
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetFullscreen(on) {
    return $Call.ByID(3237189214, on);
}

/**
 * ToggleFullscreen 全屏切换
 * @returns {$CancellablePromise<void>}
 */
export function ToggleFullscreen() {
    return $Call.ByID(954194204);
}

/**
 * ToggleMaximize 最大化 / 还原
 * @returns {$CancellablePromise<void>}
 */
export function ToggleMaximize() {
    return $Call.ByID(3752375843);
}

/**
 * UpdateDesktopLyrics 主窗口在「歌词行变化 / 播放状态变化」时调用。
 * 
 * 前端做了节流（只在内容真的变化时调用），所以这里不再去重。
 * @param {{ [_ in string]?: any } | null} payload
 * @returns {$CancellablePromise<$models.desktopLyricsSnapshot>}
 */
export function UpdateDesktopLyrics(payload) {
    return $Call.ByID(760874120, payload);
}

/**
 * UpdateDesktopWallpaper 主窗口在「换歌 / 歌词行变化 / 播放状态变化」时调用。
 * 
 * 前端做了节流（只在内容真的变化时调用），所以这里不再去重。
 * @param {{ [_ in string]?: any } | null} payload
 * @returns {$CancellablePromise<$models.desktopWallpaperSnapshot>}
 */
export function UpdateDesktopWallpaper(payload) {
    return $Call.ByID(4095740398, payload);
}
