// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService 窗口控制
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

/**
 * Backdrop 返回窗口原生材质（Mica / Acrylic…）的状态。
 * 
 * 材质只能在创建窗口时指定，所以这里同时给出「配置里的值」和「窗口当前
 * 真正生效的值」，前端据此提示用户是否需要重启。
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Backdrop() {
    return $Call.ByID(2753426771);
}

/**
 * Close 关闭窗口
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(3687130319);
}

/**
 * DesktopLyricsState 读取桌面歌词的当前状态（自带开关状态，界面据此回填按钮）。
 *
 * 注意：桌面歌词窗口不在时依然返回「配置里是否开启」，而不是报错 ——
 * 前端只想知道「现在该显示开还是关」。
 * @returns {$CancellablePromise<{ text?: string, playing?: boolean, fontSize?: number, enabled?: boolean }>}
 */
export function DesktopLyricsState() {
    return $Call.ByID(3272880628);
}

/**
 * IsFullscreen 当前是否全屏
 * @returns {$CancellablePromise<boolean>}
 */
export function IsFullscreen() {
    return $Call.ByID(1414357132);
}

/**
 * IsMaximized 当前是否最大化
 * @returns {$CancellablePromise<boolean>}
 */
export function IsMaximized() {
    return $Call.ByID(1152965621);
}

/**
 * MarkDesktopLyricsReady 桌面歌词窗口的页面加载完成后调用：把当前状态补发一次。
 * 
 * 创建窗口与页面挂载监听之间有先后差，只靠广播的话新窗口会一直空着。
 * @returns {$CancellablePromise<{ text?: string, playing?: boolean, fontSize?: number, enabled?: boolean }>}
 */
export function MarkDesktopLyricsReady() {
    return $Call.ByID(4065798619);
}

/**
 * Minimize 最小化
 * @returns {$CancellablePromise<void>}
 */
export function Minimize() {
    return $Call.ByID(3971742233);
}

/**
 * Restart 重启应用：先拉起一个新的自己，再退出当前进程。
 * 
 * 原生材质这类「只能在创建窗口时指定」的选项靠它生效。启动失败时不会退出，
 * 把错误交回前端提示，免得用户点了重启反而把应用关掉。
 * @returns {$CancellablePromise<void>}
 */
export function Restart() {
    return $Call.ByID(542969608);
}

/**
 * SetDesktopLyrics 开 / 关桌面歌词窗口（会立刻创建或隐藏那个透明窗口）。
 * @param {boolean} on
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function SetDesktopLyrics(on) {
    return $Call.ByID(285307357, on);
}

/**
 * SetFullscreen 全屏开关
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetFullscreen(on) {
    return $Call.ByID(3237189214, on);
}

/**
 * ToggleFullscreen 全屏切换
 * @returns {$CancellablePromise<void>}
 */
export function ToggleFullscreen() {
    return $Call.ByID(954194204);
}

/**
 * ToggleMaximize 最大化 / 还原
 * @returns {$CancellablePromise<void>}
 */
export function ToggleMaximize() {
    return $Call.ByID(3752375843);
}

/**
 * UpdateDesktopLyrics 主窗口把当前歌词行推给后端，由后端广播给桌面歌词窗口。
 * 
 * 用推送而不是让歌词窗口自己轮询：两个窗口共享不了播放器状态，
 * 轮询还会在暂停时白白唤醒。
 * @param {{ [_ in string]?: any }} payload
 * @returns {$CancellablePromise<{ text?: string, playing?: boolean, fontSize?: number, enabled?: boolean }>}
 */
export function UpdateDesktopLyrics(payload) {
    return $Call.ByID(760874120, payload);
}
