import { spawn } from "node:child_process";
import fs from "node:fs";
import http from "node:http";
const EDGE = ["C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe","C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe"].find((p) => fs.existsSync(p));
const PORT = 9390, BASE = "http://127.0.0.1:5173/";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const get = (p) => new Promise((res, rej) => { http.get({ host: "127.0.0.1", port: PORT, path: p }, (r) => { let d=""; r.on("data",(c)=>(d+=c)); r.on("end",()=>res(d)); }).on("error", rej); });
const child = spawn(EDGE, ["--headless=new","--disable-gpu","--no-first-run","--window-size=1440,900",`--remote-debugging-port=${PORT}`,`--user-data-dir=${process.env.TEMP}\\mp-edge-geo`,"about:blank"], { stdio: "ignore" });
let t=null;
for(let i=0;i<80;i+=1){ await sleep(250); try{const l=JSON.parse(await get("/json/list")); t=l.find(x=>x.type==="page"); if(t)break;}catch{} }
const ws=new WebSocket(t.webSocketDebuggerUrl);
const pend=new Map(); let id=0;
const send=(m,p={})=>new Promise(res=>{id+=1;pend.set(id,res);ws.send(JSON.stringify({id,method:m,params:p}));});
ws.addEventListener("message",ev=>{const m=JSON.parse(ev.data); if(m.id&&pend.has(m.id)){pend.get(m.id)(m.result);pend.delete(m.id);}});
await new Promise(r=>ws.addEventListener("open",r));
await send("Runtime.enable"); await send("Page.enable");
const ev=async(e)=>{const r=await send("Runtime.evaluate",{expression:e,returnByValue:true,awaitPromise:true}); if(r?.exceptionDetails) return {__error:r.exceptionDetails.exception?.description}; return r?.result?.value;};
await send("Page.navigate",{url:`${BASE}?probe=1&view=player&pv=arcanum&playing=1`});
await sleep(6000);
const out = await ev("(() => { const c=document.querySelector('.ar-scene'); const s=document.querySelector('.ar-stage'); const cr=c.getBoundingClientRect(); const safeTop=parseFloat(getComputedStyle(s).getPropertyValue('--ar-safe-top'))||0; const safeBottom=parseFloat(getComputedStyle(s).getPropertyValue('--ar-safe-bottom'))||0; const H=cr.height, W=cr.width; const safeH=H-safeTop-safeBottom; const visible=Math.min(W,safeH); const R=Math.max(40,(visible*0.5)/(1.18*1.42)); const cy=safeTop+safeH/2; return { W, H, safeTop, safeBottom, safeH, safeMidY: cy, R:+R.toFixed(1), outerRing:+(1.18*R).toFixed(1), maxWave:+(1.18*R*1.42).toFixed(1), circleTop:+(cy-1.18*R).toFixed(1), circleBottom:+(cy+1.18*R).toFixed(1), waveBottom:+(cy+1.18*R*1.42).toFixed(1), safeTopEdge: safeTop, safeBottomEdge: H-safeBottom, visualMid: +((safeTop + (H-safeBottom))/2).toFixed(1), fullyVisible: (cy+1.18*R*1.42) <= (H-safeBottom)+1 && (cy-1.18*R*1.42) >= safeTop-1 }; })()");
console.log(JSON.stringify(out,null,1));
ws.close(); child.kill();
