// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LibraryService 曲库相关的前端接口
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as bootstrap$0 from "./internal/bootstrap/models.js";

/**
 * AddFolder 弹出系统目录选择器并添加；用户取消时返回 cancelled=true。
 * manualPath 非空时直接使用该路径（用于手输路径或自动化测试）。
 * @param {string} manualPath
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function AddFolder(manualPath) {
    return $Call.ByID(1383348805, manualPath);
}

/**
 * Folders 返回已配置的音乐文件夹
 * @returns {$CancellablePromise<bootstrap$0.Folder[] | null>}
 */
export function Folders() {
    return $Call.ByID(2416607191);
}

/**
 * PickDirectory 单独暴露目录选择（设置界面「添加文件夹」用）
 * @returns {$CancellablePromise<string>}
 */
export function PickDirectory() {
    return $Call.ByID(3166434534);
}

/**
 * RefreshWatchers 供「设置」修改后手动刷新监听
 * @returns {$CancellablePromise<void>}
 */
export function RefreshWatchers() {
    return $Call.ByID(3669577364);
}

/**
 * RemoveFolder 移除音乐文件夹（不动本地文件）
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFolder(id) {
    return $Call.ByID(775672466, id);
}

/**
 * RevealInExplorer 在系统文件管理器中定位路径
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RevealInExplorer(path) {
    return $Call.ByID(2696454471, path);
}

/**
 * Scan 扫描指定文件夹（folderIds 为空表示全部）。
 * 立即返回是否成功启动，实际进度通过 scan:progress / scan:done 事件推送。
 * Scan 启动一次异步全量扫描。
 * 返回 started=true 表示本次调用确实会跑一次扫描并最终发出 scan:done 事件。
 * 注意：曲库内部会把并发的扫描请求排队（而不是丢弃），因此这里恒为 true，
 * 前端只需等 scan:done 即可，不会出现「等不到事件」的情况。
 * @param {string[] | null} folderIDs
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Scan(folderIDs) {
    return $Call.ByID(3812048987, folderIDs);
}

/**
 * SetWatchers 开/关文件夹实时监听
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetWatchers(enabled) {
    return $Call.ByID(3078203663, enabled);
}

/**
 * Songs 返回过滤后的全部歌曲
 * @returns {$CancellablePromise<bootstrap$0.Song[] | null>}
 */
export function Songs() {
    return $Call.ByID(4115857732);
}

/**
 * Stats 曲库统计（关于页面用）
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Stats() {
    return $Call.ByID(2363876853);
}

/**
 * ToggleLike 切换「我喜欢」状态，返回切换后的状态
 * @param {string} songID
 * @returns {$CancellablePromise<boolean>}
 */
export function ToggleLike(songID) {
    return $Call.ByID(1453136957, songID);
}
