// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LoudnessService 响度测量与补偿
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as bootstrap$0 from "./internal/bootstrap/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as loudness$0 from "./internal/loudness/models.js";

/**
 * AlbumGains 返回按专辑聚合的补偿增益（「整张专辑统一」模式）
 * 
 * 与 GainMap 同理，只对曲库内歌曲分组：在线试听曲目不属于任何本地专辑，
 * 在 album 模式下它们保持不补偿（「查不到就不抬升也不压低」，与
 * frontend/src/js/audio.js#gainDBFor 的既有安全语义一致）。
 * @param {number} targetLUFS
 * @returns {$CancellablePromise<{ [_ in string]?: number } | null>}
 */
export function AlbumGains(targetLUFS) {
    return $Call.ByID(1470889823, targetLUFS);
}

/**
 * Cancel 中止批量测量
 * @returns {$CancellablePromise<void>}
 */
export function Cancel() {
    return $Call.ByID(1203138964);
}

/**
 * Clear 清空测量缓存
 * @returns {$CancellablePromise<void>}
 */
export function Clear() {
    return $Call.ByID(2521092111);
}

/**
 * GainMap 返回「songId → 补偿增益 dB」映射，供前端批量套用。
 * 
 * ★ 换挡位零成本的落点：这张表由**已有的测量结果**现算出来，
 * 不需要为另一个挡位重新测量任何一首歌。用户从「较响」切到「默认」时，
 * 整个曲库的补偿在这一个调用里就全部就位（每首几纳秒的算术），
 * 而不是排一个几十分钟的队。
 * 
 * 没测过的歌不在其中，前端播到那首时会走 Measure 按需补算。
 * 
 * 注意这里刻意**只遍历曲库**：在线试听曲目没有稳定的「专辑归属」，
 * 把它们塞进批量表既会让这张随曲库变化的映射多出易失条目，也会让
 * 「按专辑统一」失去意义。在线曲目走 Get/Measure 的按需路径（track 模式），
 * 测出来的记录同样进缓存、下次试听直接命中。
 * @param {number} targetLUFS
 * @returns {$CancellablePromise<{ [_ in string]?: number } | null>}
 */
export function GainMap(targetLUFS) {
    return $Call.ByID(1844778349, targetLUFS);
}

/**
 * Get 取一首歌的测量结果与补偿增益。
 * 
 * ★ 换挡位是零成本的：测量结果与挡位无关，所以这里要么直接命中已缓存的
 * 该挡位增益，要么用已有的测量结果现场算一次（纯算术），**绝不会**因为
 * 「换了个挡位」就重新测量。
 * 
 * 在线试听曲目也走这里（经 songByID 的虚拟表兜底）：它们的音频在本地
 * 缓存里，测量条件与本地曲目完全一样。
 * @param {string} songID
 * @param {number} targetLUFS
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Get(songID, targetLUFS) {
    return $Call.ByID(2576807882, songID, targetLUFS);
}

/**
 * InvalidateTarget 兼容旧接口。
 * 
 * ★ 它现在**什么都不删**（返回 dropped=0）。
 * 
 * 历史上这个方法是「把 target 不等于当前值的记录全删掉」，代价是用户每换
 * 一次挡位就丢掉整库已算好的结果 —— 四个挡位来回切就是反复重算同一批歌，
 * 那正是用户报的「从较响改回默认时，较响算好的补偿丢了」。
 * 
 * 现在测量与挡位解耦：换挡位只意味着增益按新目标现算（纯算术，几纳秒），
 * 没有任何缓存需要失效。保留这个方法只是为了不动前端绑定。
 * @param {number} targetLUFS
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function InvalidateTarget(targetLUFS) {
    return $Call.ByID(3331883314, targetLUFS);
}

/**
 * Measure 测量单首歌 —— 这是常规路径：用户播到哪首就测哪首，不预先全库扫描。
 * 前端在开始播放时调用，测完立刻套用补偿。
 * 
 * 在线试听曲目同样支持：只要它的音频已经下载到本地缓存（前端播放在线曲目
 * 时后端会先 EnsureCached），就能像本地文件一样测量。测出的记录按
 * Path/Size/ModTime 进同一个缓存 —— 这几个量对在线曲目是稳定的，
 * 所以第二次试听同一首歌会直接命中缓存，不会重复跑 ffmpeg。
 * 
 * ★ 走的是**高优先级**队列（PriorityInterrupt）：如果后台正在批量预热整库，
 * 这首歌会插到队首 —— 这正是「优先处理正在播放的那首歌」。
 * @param {string} songID
 * @param {number} targetLUFS
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Measure(songID, targetLUFS) {
    return $Call.ByID(1705685682, songID, targetLUFS);
}

/**
 * MeasureAll 后台批量预热整个曲库（可选，正常使用不需要）。
 * 异步执行，进度通过 loudness:progress 事件推送。
 * 
 * ★ 它走**低优先级**队列：一旦用户点开某首歌（走 Measure 的高优先级通道），
 * 预热会让出槽位，先测用户正在听的那首。并发默认压到 2，避免把 CPU 铺满。
 * @param {number} targetLUFS
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function MeasureAll(targetLUFS) {
    return $Call.ByID(22522345, targetLUFS);
}

/**
 * RefreshTools 重新探测 ffmpeg（设置界面点「重新检测」时用）
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function RefreshTools() {
    return $Call.ByID(830981436);
}

/**
 * State 返回响度测量能力与进度概况
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function State() {
    return $Call.ByID(162640547);
}

/**
 * StoreMeasurement 把「转码时顺手算出来」的测量结果记进缓存。
 * 
 * 由 main 装配层挂在 media.Server 的扫描钩子上（见 SetLoudnessSink）。
 * 它是响度测量**唯一不需要跑 ffmpeg 的入口**：转码播放本来就要解码整首歌，
 * 顺手把响度算出来即可，不再需要第二遍解码。
 * 
 * 这里同时把当前挡位的增益算好记下（GainFor 会做），这样播放到这首歌时
 * 补偿已经就位 —— 用户感受到的是「响度均衡不需要等待」。
 * @param {bootstrap$0.Song} song
 * @param {loudness$0.Measurement} res
 * @returns {$CancellablePromise<void>}
 */
export function StoreMeasurement(song, res) {
    return $Call.ByID(3202837413, song, res);
}
