// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LoudnessService 响度测量与补偿
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

/**
 * AlbumGains 返回按专辑聚合的补偿增益（「整张专辑统一」模式）
 * @param {number} targetLUFS
 * @returns {$CancellablePromise<{ [_ in string]?: number } | null>}
 */
export function AlbumGains(targetLUFS) {
    return $Call.ByID(1470889823, targetLUFS);
}

/**
 * Cancel 中止批量测量
 * @returns {$CancellablePromise<void>}
 */
export function Cancel() {
    return $Call.ByID(1203138964);
}

/**
 * Clear 清空测量缓存
 * @returns {$CancellablePromise<void>}
 */
export function Clear() {
    return $Call.ByID(2521092111);
}

/**
 * GainMap 返回「songId → 补偿增益 dB」映射，供前端批量套用。
 * 
 * 只包含当前标准下**有效**的缓存；没测过的歌不在其中，
 * 前端播到那首时会走 Measure 按需补算。
 * @param {number} targetLUFS
 * @returns {$CancellablePromise<{ [_ in string]?: number } | null>}
 */
export function GainMap(targetLUFS) {
    return $Call.ByID(1844778349, targetLUFS);
}

/**
 * Get 取一首歌的测量结果与补偿增益（当前标准下未测量则 measured=false）
 * @param {string} songID
 * @param {number} targetLUFS
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Get(songID, targetLUFS) {
    return $Call.ByID(2576807882, songID, targetLUFS);
}

/**
 * InvalidateTarget 让不等于给定标准的缓存全部失效。
 * 设置界面改了目标响度/算法后调用：清掉旧补偿，之后播放时按需重算。
 * @param {number} targetLUFS
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function InvalidateTarget(targetLUFS) {
    return $Call.ByID(3331883314, targetLUFS);
}

/**
 * Measure 测量单首歌 —— 这是常规路径：用户播到哪首就测哪首，不预先全库扫描。
 * 前端在开始播放时调用，测完立刻套用补偿。
 * @param {string} songID
 * @param {number} targetLUFS
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Measure(songID, targetLUFS) {
    return $Call.ByID(1705685682, songID, targetLUFS);
}

/**
 * MeasureAll 后台批量预热整个曲库（可选，正常使用不需要）。
 * 异步执行，进度通过 loudness:progress 事件推送。
 * @param {number} targetLUFS
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function MeasureAll(targetLUFS) {
    return $Call.ByID(22522345, targetLUFS);
}

/**
 * RefreshTools 重新探测 ffmpeg（设置界面点「重新检测」时用）
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function RefreshTools() {
    return $Call.ByID(830981436);
}

/**
 * State 返回响度测量能力与进度概况
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function State() {
    return $Call.ByID(162640547);
}
