// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlaylistService 歌单接口
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as bootstrap$0 from "./internal/bootstrap/models.js";

/**
 * AddSongs 批量加入歌单（去重）
 * 
 * 歌单 id 不存在时必须**报错**，不能返回 (0, nil)：调用方（前端）拿到
 * added=0 会理解成「这些歌本来就在里面」，而真实原因是「后端根本没有这个歌单」，
 * 于是内存里的歌单看着加进去了、config.json 里一首都没有。
 * @param {string} id
 * @param {string[] | null} songIDs
 * @returns {$CancellablePromise<number>}
 */
export function AddSongs(id, songIDs) {
    return $Call.ByID(2215414596, id, songIDs);
}

/**
 * Create 新建歌单
 * @param {string} name
 * @returns {$CancellablePromise<bootstrap$0.Playlist>}
 */
export function Create(name) {
    return $Call.ByID(2865002187, name);
}

/**
 * Delete 删除歌单（不动本地文件）；「我喜欢」不可删除
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(285555208, id);
}

/**
 * Export 导出 m3u 到歌单所在目录（返回写入的文件路径）
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function Export(id) {
    return $Call.ByID(1688012977, id);
}

/**
 * List 返回全部歌单（第一个固定是「我喜欢」）
 * @returns {$CancellablePromise<bootstrap$0.Playlist[] | null>}
 */
export function List() {
    return $Call.ByID(2755327747);
}

/**
 * RemoveSongs 从歌单移除（「我喜欢」请用 Library.ToggleLike）
 * @param {string} id
 * @param {string[] | null} songIDs
 * @returns {$CancellablePromise<number>}
 */
export function RemoveSongs(id, songIDs) {
    return $Call.ByID(3097791599, id, songIDs);
}

/**
 * Rename 重命名歌单
 * @param {string} id
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function Rename(id, name) {
    return $Call.ByID(3332856657, id, name);
}

/**
 * Reorder 调整歌单内歌曲顺序（前端拖拽排序后调用，用于持久化）
 * 
 * 「我喜欢」的歌曲顺序存在 config.LikedIDs 而不是 Playlists 里，
 * 这里必须单独处理：否则拖拽「我喜欢」的队列时后端静默什么都不做
 * （队列里有歌单里没有的歌时，前端还会把这次拖拽写回歌单 —— 见 store#reorderQueue）。
 * @param {string} id
 * @param {number} $from
 * @param {number} to
 * @returns {$CancellablePromise<void>}
 */
export function Reorder(id, $from, to) {
    return $Call.ByID(999478946, id, $from, to);
}

/**
 * ReorderPlaylists 调整侧边栏歌单顺序（from/to 为「不含我喜欢」的下标）
 * @param {number} $from
 * @param {number} to
 * @returns {$CancellablePromise<void>}
 */
export function ReorderPlaylists($from, to) {
    return $Call.ByID(1221098597, $from, to);
}
