// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlayerService 把播放能力暴露给前端。
 * 
 * 线程模型：所有方法都可能被 Wails 的绑定层从任意 goroutine 调用，
 * 因此对引擎的复合操作（换歌 = 解析地址 + 转码 + 装载）用 mu 串行化，
 * 避免两次快速切歌互相覆盖。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

/**
 * Available 报告后端音频是否可用。前端在启动时调一次，
 * 决定走「后端播放」还是「回退到 <audio>」。
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Available() {
    return $Call.ByID(3719494475);
}

/**
 * CancelTrackGap 取消可能还挂着的「切歌间隔」，不改变当前播放的内容。
 * 
 * 供前端在**明确的即时切歌意图**上调用，好让「用户意图 → 出声」的窗口不被
 * 一次多余的等待拉长。引擎的 Load / Play 各自也会取消（见那里的说明），
 * 所以它不是唯一的一道 —— 先发它只是把窗口压到最短，并让
 * 「间隔里用户点了下一首」这种时序有一个确定的落点。
 * 
 * 播放器还没装载、或本来就没有间隔时，它同样是安全的空操作。
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function CancelTrackGap() {
    return $Call.ByID(1619335283);
}

/**
 * Diagnostics 返回引擎诊断信息（供设置界面排查「声音断续」）
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Diagnostics() {
    return $Call.ByID(852526004);
}

/**
 * Effect 返回当前音效档位（供前端挂载时对齐状态）。
 * 
 * 同时返回"请求值"与"音频线程实际生效值"：两者在切换后可能差一个
 * 缓冲周期，正常情况下应当一致；不一致说明音频回调没有在推进
 * （声卡没开、或者引擎卡住了），诊断时很有用。
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Effect() {
    return $Call.ByID(1883364337);
}

/**
 * Load 装载一首歌并（按 state 里的播放意图）开始播放。
 * 
 * 这个方法会**阻塞**到歌曲可以起播为止（需要转码时可能几秒）。
 * 前端应当把它当作「切歌」来用，并在此期间显示加载态。
 * 
 * ★ 它是「手动切歌」的入口，因此**不会有**切歌间隔的停顿：
 * 引擎的 Load 会把上一首播完留下的那个间隔作废（见 audioplay.Engine.Load）。
 * 自动切歌（上一首播完，见 setEOFHandler）**不**走这里 —— 它只发一条
 * player:ended 事件，之后由前端决定放哪首，间隔在那一刻也已经走完了。
 * 换句话说：间隔只花在「自动接下一首」上，手动点的一下永远是立即的。
 * @param {string} songID
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Load(songID) {
    return $Call.ByID(3996494492, songID);
}

/**
 * Pause 暂停
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Pause() {
    return $Call.ByID(191671602);
}

/**
 * Play 开始播放（不换歌）
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Play() {
    return $Call.ByID(1808111650);
}

/**
 * Playing 报告引擎当前是否在出声。
 * 
 * 给媒体键的退化路径用：前端还没挂上监听时，按键直接在这里做「在放就停、
 * 停了就放」的翻转，至少不让按键静默丢掉。
 * 
 * 注意它问的是**引擎**而不是前端 store 的播放意图 —— 两者在切歌途中
 * 会短暂不一致（后端还要把环形缓冲里的旧音频吐完）。对「退化的兜底行为」
 * 而言，引擎的真实状态才是该依据的那个。
 * @returns {$CancellablePromise<boolean>}
 */
export function Playing() {
    return $Call.ByID(2882669630);
}

/**
 * Seek 跳到指定毫秒。会做范围钳制，非法值不会让播放错乱。
 * @param {number} positionMs
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Seek(positionMs) {
    return $Call.ByID(1479346536, positionMs);
}

/**
 * SetEffect 设置音效档位（清澈人声 / 3D 环绕 / 混响等）。
 * 
 * 取值见 audioplay.EffectPresets；非法值会被收敛到 off，不报错 ——
 * 音效是"锦上添花"的功能，为一个非法字符串让播放失败是本末倒置。
 * 
 * 这个方法**不需要**在装载时一起传（不像 SetGain）：音效是跨歌的偏好，
 * 换歌时引擎会清空 DSP 状态但保留档位（见 audioplay.Engine.Load）。
 * 所以前端只需在设置变化时调一次。
 * 
 * 返回载荷里带上实际生效的档位与中文名，供设置界面回显 ——
 * 前端传了非法值时能立刻看到"其实落回了关闭"，而不是界面显示一套、
 * 实际生效另一套。
 * @param {string} preset
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function SetEffect(preset) {
    return $Call.ByID(1919586049, preset);
}

/**
 * SetLoudnessGain 同步当前歌曲的响度补偿（dB）。
 * 前端算好（或从后端响度服务取到）后通过这里下发，避免后端重复一套响度逻辑。
 * @param {number} gainDB
 * @returns {$CancellablePromise<void>}
 */
export function SetLoudnessGain(gainDB) {
    return $Call.ByID(1065547244, gainDB);
}

/**
 * SetPlaybackOptions 同步「跳过静音」与「切歌间隔」这几个播放选项。
 * 
 * 它是设置界面改完开关后**立刻**调用的：跳过静音要影响的是「下一首」，
 * 而切歌间隔可能正好在等 —— 所以间隔在这里就地重建，用户改完不必重启。
 * 
 * 参数用显式的三个值而不是一个结构体：Wails 的绑定生成器对匿名结构体、
 * map 之外的自定义类型支持都不好（见 setApp 里关于 non-empty interface 的说明），
 * 三个标量参数是最省事也最不容易出错的形式。
 * 
 * enabled=false 时把两个跳过开关一起关掉，用于「恢复默认」这类场景。
 * @param {boolean} skipSilenceHead
 * @param {boolean} skipSilenceTail
 * @param {number} trackGapSeconds
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function SetPlaybackOptions(skipSilenceHead, skipSilenceTail, trackGapSeconds) {
    return $Call.ByID(904562217, skipSilenceHead, skipSilenceTail, trackGapSeconds);
}

/**
 * SetVolume 同步用户音量（0..1）与静音状态。
 * 真正的增益 = 用户音量 × 响度补偿，在 applyGainLocked 里合成。
 * @param {number} volume
 * @param {boolean} muted
 * @returns {$CancellablePromise<void>}
 */
export function SetVolume(volume, muted) {
    return $Call.ByID(671101282, volume, muted);
}

/**
 * Spectrum 返回当前频谱（0..1 的数组）。拿不到时 bands 为 nil。
 * 
 * bands 参数是皮肤声明的段数（见 contract.js 的 spectrum 字段）。
 * 越界会被钳到 1..128，与前端 audio.js#spectrum 的口径一致。
 * @param {number} bands
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Spectrum(bands) {
    return $Call.ByID(3765431919, bands);
}

/**
 * Start 打开声卡。失败**不是**致命错误：返回 available=false，
 * 前端会退回用 <audio> 播放（见 audio.js 的回退分支）。
 * @returns {$CancellablePromise<boolean>}
 */
export function Start() {
    return $Call.ByID(2217041500);
}

/**
 * State 返回当前播放状态 + 位置锚点。
 * 前端在挂载、从后台恢复、或怀疑自己漂移时调一次重新对齐。
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function State() {
    return $Call.ByID(2570357237);
}

/**
 * Stop 关闭声卡（退出时调用）
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2311398648);
}

/**
 * Tick 由后端的定时器周期调用：负责在「没有状态变化但位置在走」时补推锚点。
 * 
 * 为什么需要它：锚点只靠前端调 Play/Pause/Seek 时推是不够的 ——
 * 播放过程中没有任何一个 API 会被调用，前端却需要持续重新对齐。
 * 由后端主动节流推送，前端就不必轮询。
 * @returns {$CancellablePromise<void>}
 */
export function Tick() {
    return $Call.ByID(3140624317);
}

/**
 * Unload 停止播放并卸载当前歌曲（前端清空播放队列 / 停止时调用）
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Unload() {
    return $Call.ByID(1154023315);
}
