// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UnplayableService 记录并管理「播放失败」的文件清单。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "/wails/runtime.js";

/**
 * Clear 清空整个清单。
 * @returns {$CancellablePromise<number>}
 */
export function Clear() {
    return $Call.ByID(1505288485);
}

/**
 * Count 返回条目数（前端启动时用来决定要不要显示提示角标）。
 * @returns {$CancellablePromise<number>}
 */
export function Count() {
    return $Call.ByID(3651112887);
}

/**
 * Forget 忘掉一首歌的失败记录，**并让它可以重新进曲库**。
 * 
 * 与 Remove 的区别：Remove 只是把提示抹掉（不动曲库），Forget 是
 * 「我修好文件了，让它回来」。前端在重新扫描前调用。
 * 
 * 曲库那边不需要额外动作：重新扫描本来就会重新遍历磁盘，
 * 之前被 DropSong 摘掉的歌会被重新发现。
 * @param {string} songID
 * @returns {$CancellablePromise<boolean>}
 */
export function Forget(songID) {
    return $Call.ByID(1528466513, songID);
}

/**
 * List 返回全部「放不出来」的文件（最近失败的在前）。
 * @returns {$CancellablePromise<({ [_ in string]?: any } | null)[] | null>}
 */
export function List() {
    return $Call.ByID(1053766560);
}

/**
 * Remove 把一条记录从清单里删掉（用户在设置页点「忽略 / 已知悉」）。
 * 
 * 语义：**只删记录，不改曲库**。用户想让这首歌重回曲库就点「重新扫描」
 * （见 Restore），这里不做隐式的事情。
 * @param {string} songID
 * @returns {$CancellablePromise<boolean>}
 */
export function Remove(songID) {
    return $Call.ByID(2046830528, songID);
}

/**
 * Report 登记一首「播放失败」的歌。前端在 playback failure 时调用。
 * 
 * 参数：
 *   - songID  歌曲 id（必填）
 *   - reason  失败原因原文（来自后端错误或 <audio> 的错误码说明）
 *   - path    文件路径（前端已知时传，便于用户在清单里认出是哪个文件）
 * 
 * 返回登记后的条目（同一首歌重复上报会合并：次数累加、时间刷新、
 * 原因以最新一次为准 —— 因为文件可能被换成另一种坏法）。
 * @param {string} songID
 * @param {string} reason
 * @param {string} path
 * @returns {$CancellablePromise<{ [_ in string]?: any } | null>}
 */
export function Report(songID, reason, path) {
    return $Call.ByID(1134346882, songID, reason, path);
}
