// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * Config 应用配置（落盘为 JSON，可直接手改）
 * @typedef {$models.Config} Config
 */

/**
 * FilterRule 过滤规则，语义与前端 store.js#matchRules 完全一致：
 *   - exclude 命中即排除（优先）
 *   - 存在启用的 include 规则时，必须至少命中一条才保留
 * @typedef {$models.FilterRule} FilterRule
 */

/**
 * Folder 一个被监听的本地音乐目录
 * @typedef {$models.Folder} Folder
 */

/**
 * Playlist 歌单；「我喜欢」是受限歌单（Locked=true，不可删除）
 * @typedef {$models.Playlist} Playlist
 */

/**
 * Song 一首本地歌曲
 * @typedef {$models.Song} Song
 */
