// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Config 应用配置（落盘为 JSON，可直接手改）
 * @typedef {Object} Config
 * @property {string} theme
 * @property {string} themeMode - dark | light | system
 * @property {number} glassBlur
 * @property {number} glassAlpha
 * @property {boolean} animations
 * @property {boolean} accentFromCover
 * @property {boolean} showAlbumColumn
 * @property {boolean} showLyrics
 * @property {string} playMode - sequence | loop-all | loop-one | shuffle
 * @property {number} volume
 * @property {boolean} muted
 * @property {string} playerViewMode - classic | immersive | minimal
 * @property {boolean} autoScanOnStart
 * @property {boolean} watchFolders
 * @property {number} scanConcurrency
 * @property {number} lyricsFontSize
 * @property {number} lyricsLines
 * @property {string[] | null} lyricsSources
 * @property {Folder[] | null} folders
 * @property {FilterRule[] | null} filterRules
 * @property {string[] | null} likedIds
 * @property {Playlist[] | null} playlists
 * @property {string} cacheDir
 */

/**
 * FilterRule 过滤规则，语义与前端 store.js#matchRules 完全一致：
 *   - exclude 命中即排除（优先）
 *   - 存在启用的 include 规则时，必须至少命中一条才保留
 * @typedef {Object} FilterRule
 * @property {string} id
 * @property {string} type - size | regex
 * @property {string} op - size: lt|lte|gt|gte|eq   regex: match
 * @property {string} value - size: 数字   regex: 正则源码
 * @property {string} unit - B | KB | MB | GB
 * @property {string} scope - exclude | include
 * @property {boolean} enabled
 */

/**
 * Folder 一个被监听的本地音乐目录
 * @typedef {Object} Folder
 * @property {string} id
 * @property {string} path
 * @property {number} trackCount
 * @property {string} status - ok | missing | denied
 * @property {boolean} watching
 * @property {number} addedAt
 */

/**
 * Playlist 歌单；「我喜欢」是受限歌单（Locked=true，不可删除）
 * @typedef {Object} Playlist
 * @property {string} id
 * @property {string} name
 * @property {boolean} locked
 * @property {boolean} builtin
 * @property {string[] | null} songIds
 * @property {number} createdAt
 */

/**
 * Song 一首本地歌曲
 * @typedef {Object} Song
 * @property {string} id
 * @property {string} path
 * @property {string} title
 * @property {string} artist
 * @property {string} album
 * @property {string} ext
 * @property {number} duration - 毫秒
 * @property {number} size - 字节
 * @property {number} sampleRate
 * @property {number} bitrate
 * @property {number} addedAt
 * @property {number} playCount
 * @property {string} cover - data URL；无封面时为空字符串
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
